{% set version = "0.0.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggtangle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggtangle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggtangle/ggtangle_{{ version }}.tar.gz
  sha256: c77c6c4c17c1ba4f60ec8ce7b4bfdcc71300fb1003010a5873ff9a3f684b7b62

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggfun >=0.1.7
    - r-ggplot2
    - r-ggrepel
    - r-igraph
    - r-rlang
    - r-yulab.utils >=0.1.7
  run:
    - r-base
    - r-ggfun >=0.1.7
    - r-ggplot2
    - r-ggrepel
    - r-igraph
    - r-rlang
    - r-yulab.utils >=0.1.7

test:
  commands:
    - $R -e "library('ggtangle')"           # [not win]
    - "\"%R%\" -e \"library('ggtangle')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggtangle
  license: Artistic-2.0
  summary: Extends the 'ggplot2' plotting system to support network visualization. Inspired by the 'Method 1' in 'ggtree' (G Yu (2018) <doi:10.1093/molbev/msy194>), 'ggtangle' is designed to work with network associated data.
  license_family: OTHER
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0'

extra:
  recipe-maintainers:
    - conda-forge/r


# Package: ggtangle
# Title: Draw Network with Data
# Version: 0.0.6
# Authors@R: c( person(given = "Guangchuang", family = "Yu", email = "guangchuangyu@gmail.com",   role  = c("aut", "cre"), comment = c(ORCID = "0000-0002-6485-8781")))
# Description: Extends the 'ggplot2' plotting system to support network visualization. Inspired by the 'Method 1' in 'ggtree' (G Yu (2018) <doi:10.1093/molbev/msy194>), 'ggtangle' is designed to work with network associated data.
# Imports: ggfun (>= 0.1.7), ggplot2, ggrepel, igraph, rlang, yulab.utils (>= 0.1.7)
# Suggests: aplot, cli, ggnewscale, ggtree, knitr, prettydoc, rmarkdown, scatterpie (>= 0.2.4)
# VignetteBuilder: knitr
# License: Artistic-2.0
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# NeedsCompilation: no
# Packaged: 2024-12-18 10:15:21 UTC; HUAWEI
# Author: Guangchuang Yu [aut, cre] (<https://orcid.org/0000-0002-6485-8781>)
# Maintainer: Guangchuang Yu <guangchuangyu@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-12-18 14:30:06 UTC
